Project 1: Setup and mobile version skeleton
Nelitaa/Portfolio pull request #1
Opened 2022-09-22 21:42 UTC by Nelitaa

- Create a new GitHub repo.
- Create a new branch
- Add a .gitignore file.
- Set up [a linter for HTML and CSS]
- Add a descriptive README file to the project.
- Add gulpfile.js file
- Add a .html and .css file to build the first 2 sections of the mobile website using template number 5. (the toolbar and the headline section)

2022-09-22 22:49 UTC, Chimwemwe-127001 requested changes
# Required Changes ♻️ :warning: 
### Hi @Nelitaa

Good job so far! :tada: 

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand: 

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif" alt="so close">

## Highlight :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:

## Required Changes ♻️

***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-22 22:49 UTC, Chimwemwe-127001 commented on index.html
> +    </div>
- According to the project requirements, there are two sections you need to build for this project, the toolbar and the headline section
- [ ] I suggest you wrap the `header` tag around the hamburger menu. Typically the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.
- [ ] I also suggest you create a section tag for the remaining content because. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.
- [ ] As the requirements suggest, make sure you lay out the elements in both sections with flexbox

2022-09-22 22:49 UTC, Chimwemwe-127001 commented on index.html
> +            <button type="button">Start collaboration</button>
- [ ] As the requirements suggest, implement the button interactions (enable, hover, etc.).

2022-09-22 22:49 UTC, Chimwemwe-127001 commented on css/styles.css
> +}
- [ ] Consider avoiding the use of position: absolute; width and height in these cases because these are affecting the responsiveness of the website

2022-09-23 18:11 UTC, Nelitaa commented on index.html
> +    </div>
I already corrected it, thanks

2022-09-23 18:11 UTC, Nelitaa commented on index.html
> +            <button type="button">Start collaboration</button>
I already corrected it, thanks

2022-09-23 18:11 UTC, Nelitaa commented on css/styles.css
> +}
I already corrected it, thanks

2022-09-23 18:28 UTC, jerryowusu approved these changes
Hi @Nelitaa :wave:,  

Your project is complete!  There is nothing else to say other than... it's time to merge it :medal_sports: Congratulations! 🎉 

![approved-target-lady](https://user-images.githubusercontent.com/65233860/192033277-eec0fe15-efa6-48cb-8d63-0ae9c4b6f87a.gif)


## Highlights
:heavy_check_mark: Good commit messages
:heavy_check_mark: Neat and well organized code
:heavy_check_mark: Excellent readme file

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 20:01 UTC, merged